# Generated by Django 6.0.5 on 2026-06-01 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('search_text', models.TextField(blank=True, default='', editable=False)),
                ('type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('post', 'Post'), ('note', 'Note'), ('hadith', 'Hadith / Verse')], db_index=True, max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=300, unique=True)),
                ('body', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='featured_images/')),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audios/%Y/%m/%d/')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('original_text', models.TextField(blank=True)),
                ('translated_text', models.TextField(blank=True)),
                ('source_attribution', models.CharField(blank=True, max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss', to='base.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='%(class)ss', to='base.tag')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Content',
                'ordering': ('-created_at',),
                'abstract': False,
                'indexes': [models.Index(fields=['is_published', 'is_archived', 'created_at'], name='content_con_is_publ_f2d6ba_idx'), models.Index(fields=['is_published', 'is_archived', 'publish_at'], name='content_con_is_publ_01c910_idx'), models.Index(fields=['type', 'is_published', 'is_archived'], name='content_con_type_855080_idx')],
            },
        ),
    ]
