# Generated by Django 6.0.5 on 2026-06-04 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
