# Generated by Django 6.0.5 on 2026-06-01 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='content.content'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='content.content'),
        ),
        migrations.AddField(
            model_name='contentprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyguidance',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='daily_guidances', to='content.content'),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='content.content'),
        ),
        migrations.AddField(
            model_name='saveditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content', 'status'], name='base_commen_content_f59593_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentprogress',
            unique_together={('user', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='saveditem',
            unique_together={('user', 'content')},
        ),
    ]
